"""
Graph OLAP Schemas - Shared Pydantic schemas for the Graph OLAP Platform.

This package provides validated Pydantic models for:
- Mapping definitions (nodes, edges, properties)
- API request/response structures
- Internal component communication
- Common patterns (pagination, errors)

All schemas are derived from the authoritative documentation in docs/.

Usage:
    # Import definition schemas
    from graph_olap_schemas import NodeDefinition, EdgeDefinition, PropertyDefinition

    # Import API schemas
    from graph_olap_schemas import CreateMappingRequest, MappingResponse

    # Import constants
    from graph_olap_schemas import RyugraphType, CYPHER_RESERVED_WORDS

    # Import response wrappers
    from graph_olap_schemas import DataResponse, PaginatedResponse, ErrorResponse
"""

from graph_olap_schemas.api_algorithms import (
    AlgorithmCategory,
    AlgorithmExecutionResponse,
    AlgorithmInfoResponse,
    AlgorithmListResponse,
    AlgorithmParameterInfo,
    AlgorithmType,
    ExecutionStatus,
    NativeAlgorithmRequest,
    NetworkXAlgorithmRequest,
)
from graph_olap_schemas.api_common import (
    DataResponse,
    ErrorDetail,
    ErrorResponse,
    FilterParams,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PaginationParams,
    SortParams,
)
from graph_olap_schemas.api_internal import (
    CreateExportJobsRequest,
    ExportJobDefinition,
    ExportJobResponse,
    ExportJobsCreatedResponse,
    ExportJobStatus,
    GraphStats,
    InstanceMappingResponse,
    InstanceProgressStep,
    ShutdownBlockedResponse,
    ShutdownRequest,
    ShutdownResponse,
    SnapshotProgress,
    UpdatedResponse,
    UpdateExportJobRequest,
    UpdateInstanceMetricsRequest,
    UpdateInstanceProgressRequest,
    UpdateInstanceStatusRequest,
    UpdateSnapshotStatusRequest,
)
from graph_olap_schemas.api_ops import (
    BulkDeleteFilters,
    BulkDeleteRequest,
    BulkDeleteResponse,
    ConcurrencyConfig,
    ConcurrencyConfigResponse,
    E2ECleanupResponse,
    ExportConfigRequest,
    ExportConfigResponse,
    ExportJobsListResponse,
    ExportJobSummary,
    JobsStatusResponse,
    JobStatus,
    LifecycleConfigRequest,
    LifecycleConfigResponse,
    MaintenanceModeRequest,
    MaintenanceModeResponse,
    ResourceLifecycleConfig,
    SystemStateResponse,
    TriggerJobRequest,
    TriggerJobResponse,
)
from graph_olap_schemas.api_resources import (
    CreateInstanceFromMappingRequest,
    CreateInstanceRequest,
    CreateMappingRequest,
    CreateSnapshotRequest,
    EdgeDiffResponse,
    InstanceErrorCode,
    InstanceResponse,
    InstanceStatus,
    LifecycleResponse,
    LockStatusResponse,
    MappingDiffChangesResponse,
    MappingDiffDataResponse,
    MappingDiffResponse,
    MappingDiffSummaryResponse,
    MappingResponse,
    MappingSummaryResponse,
    MappingTreeInstanceItem,
    MappingTreeResponse,
    MappingTreeSnapshotItem,
    MappingTreeTotals,
    MappingTreeVersionItem,
    MappingVersionResponse,
    MappingVersionSummaryResponse,
    NodeDiffResponse,
    SnapshotResponse,
    SnapshotStatus,
    UpdateLifecycleRequest,
    UpdateMappingRequest,
)
from graph_olap_schemas.api_schema import (
    CacheStatsResponse,
    CatalogResponse,
    ColumnResponse,
    SchemaResponse,
    TableResponse,
)
from graph_olap_schemas.api_wrapper import (
    EdgeTableSchema,
    HealthResponse,
    LockInfo,
    NodeTableSchema,
    QueryRequest,
    QueryResponse,
    StatusResponse,
    WrapperLockStatusResponse,
    WrapperSchemaResponse,
)
from graph_olap_schemas.constants import (
    CYPHER_RESERVED_WORDS,
    EDGE_TYPE_PATTERN,
    ISO8601_DURATION_PATTERN,
    ISO8601_TIMESTAMP_PATTERN,
    MAX_DESCRIPTION_LENGTH,
    MAX_EDGE_TYPE_LENGTH,
    MAX_NODE_LABEL_LENGTH,
    MAX_PROPERTIES_PER_ENTITY,
    MAX_PROPERTY_NAME_LENGTH,
    MAX_RESOURCE_NAME_LENGTH,
    MIN_NAME_LENGTH,
    NODE_LABEL_PATTERN,
    PROPERTY_NAME_PATTERN,
    SOFT_PROPERTIES_PER_ENTITY,
    SYSTEM_PREFIXES,
    ChangeType,
    RyugraphType,
    is_reserved_name,
)
from graph_olap_schemas.definitions import (
    EdgeDefinition,
    NodeDefinition,
    PrimaryKeyDefinition,
    PropertyDefinition,
)
from graph_olap_schemas.json_schema import (
    export_all_schemas,
    export_api_algorithm_schemas,
    export_api_common_schemas,
    export_api_internal_schemas,
    export_api_ops_schemas,
    export_api_resource_schemas,
    export_api_wrapper_schemas,
    export_definition_schemas,
    get_combined_schema,
    get_schema,
    get_schema_json,
)
from graph_olap_schemas.wrapper_capabilities import (
    WRAPPER_CAPABILITIES,
    WrapperCapabilities,
    get_wrapper_capabilities,
)
from graph_olap_schemas.wrapper_interface import WrapperType

__version__ = "1.0.0"

__all__ = [
    "CYPHER_RESERVED_WORDS",
    "EDGE_TYPE_PATTERN",
    "ISO8601_DURATION_PATTERN",
    "ISO8601_TIMESTAMP_PATTERN",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_EDGE_TYPE_LENGTH",
    "MAX_NODE_LABEL_LENGTH",
    "MAX_PROPERTIES_PER_ENTITY",
    "MAX_PROPERTY_NAME_LENGTH",
    "MAX_RESOURCE_NAME_LENGTH",
    "MIN_NAME_LENGTH",
    "NODE_LABEL_PATTERN",
    "PROPERTY_NAME_PATTERN",
    "SOFT_PROPERTIES_PER_ENTITY",
    "SYSTEM_PREFIXES",
    "WRAPPER_CAPABILITIES",
    "AlgorithmCategory",
    "AlgorithmExecutionResponse",
    "AlgorithmInfoResponse",
    "AlgorithmListResponse",
    "AlgorithmParameterInfo",
    # API Algorithms
    "AlgorithmType",
    "BulkDeleteFilters",
    "BulkDeleteRequest",
    "BulkDeleteResponse",
    "CacheStatsResponse",
    # E2E Test Cleanup
    "E2ECleanupResponse",
    # API Schema Metadata
    "CatalogResponse",
    # Constants
    "ChangeType",
    "ColumnResponse",
    "ConcurrencyConfig",
    "ConcurrencyConfigResponse",
    "CreateExportJobsRequest",
    "CreateInstanceFromMappingRequest",
    "CreateInstanceRequest",
    "CreateMappingRequest",
    "CreateSnapshotRequest",
    "DataResponse",
    "EdgeDefinition",
    "EdgeDiffResponse",
    "ErrorDetail",
    "ErrorResponse",
    "ExecutionStatus",
    "ExportConfigRequest",
    "ExportConfigResponse",
    "ExportJobDefinition",
    "ExportJobResponse",
    # API Internal
    "ExportJobStatus",
    "ExportJobSummary",
    "ExportJobsCreatedResponse",
    "ExportJobsListResponse",
    "FilterParams",
    "GraphStats",
    "InstanceErrorCode",
    "InstanceMappingResponse",
    "InstanceProgressStep",
    "InstanceResponse",
    "InstanceStatus",
    # API Ops
    "JobStatus",
    "JobsStatusResponse",
    "LifecycleConfigRequest",
    "LifecycleConfigResponse",
    "LifecycleResponse",
    "LockStatusResponse",
    "MaintenanceModeRequest",
    "MaintenanceModeResponse",
    "MappingDiffChangesResponse",
    "MappingDiffDataResponse",
    "MappingDiffResponse",
    "MappingDiffSummaryResponse",
    "MappingResponse",
    "MappingSummaryResponse",
    "MappingTreeInstanceItem",
    "MappingTreeResponse",
    "MappingTreeSnapshotItem",
    "MappingTreeTotals",
    "MappingTreeVersionItem",
    "MappingVersionResponse",
    "MappingVersionSummaryResponse",
    # API Common
    "Meta",
    "NativeAlgorithmRequest",
    "NetworkXAlgorithmRequest",
    "NodeDefinition",
    "NodeDiffResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationParams",
    "PrimaryKeyDefinition",
    # Definitions
    "PropertyDefinition",
    "ResourceLifecycleConfig",
    "RyugraphType",
    "SchemaResponse",
    "ShutdownBlockedResponse",
    "ShutdownRequest",
    "ShutdownResponse",
    "SnapshotProgress",
    "SnapshotResponse",
    # API Resources
    "SnapshotStatus",
    "SortParams",
    "SystemStateResponse",
    "TableResponse",
    "TriggerJobRequest",
    "TriggerJobResponse",
    "UpdateExportJobRequest",
    "UpdateInstanceMetricsRequest",
    "UpdateInstanceProgressRequest",
    "UpdateInstanceStatusRequest",
    "UpdateLifecycleRequest",
    "UpdateMappingRequest",
    "UpdateSnapshotStatusRequest",
    "UpdatedResponse",
    "WrapperCapabilities",
    # Wrapper Interface
    "WrapperType",
    # Wrapper API (SDK ↔ Wrapper communication)
    "QueryRequest",
    "QueryResponse",
    "HealthResponse",
    "LockInfo",
    "WrapperLockStatusResponse",
    "NodeTableSchema",
    "EdgeTableSchema",
    "WrapperSchemaResponse",
    "StatusResponse",
    "export_all_schemas",
    "export_api_algorithm_schemas",
    "export_api_common_schemas",
    "export_api_internal_schemas",
    "export_api_ops_schemas",
    "export_api_resource_schemas",
    "export_api_wrapper_schemas",
    "export_definition_schemas",
    "get_combined_schema",
    # JSON Schema utilities
    "get_schema",
    "get_schema_json",
    "get_wrapper_capabilities",
    "is_reserved_name",
]
