apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyter-labs.fullname" . }}-credentials
  labels:
    {{- include "jupyter-labs.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.env.e2eTestUsername | quote }}
  api-url: {{ .Values.env.controlPlaneUrl | quote }}
